head.load(
	"js/lib/jquery.min.js",
	"js/lib/slick.min.js",
	"js/lib/canvas.js",
	"js/lib/jquery.backgroundcover.min.js",
	"js/lib/jquery.fancybox.js",
	"js/lib/jquery.form-validator.min.js",
	"js/lib/jquery.fullPage.min.js",
	"js/lib/jquery.inview.min.js",
	"js/lib/snap.svg-min.js",
	"js/lib/clipboard.min.js",
	"js/common.js"
);